name: pagination_view
description: Flutter package to simplify pagination of list of items from the internet.
version: 2.0.0
issue_tracker: https://github.com/excogitatr/pagination_view/issues
homepage: https://github.com/excogitatr/pagination_view

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^2.0.1

  # Testing
  bloc_test: ^9.0.3
  mockito: ^5.1.0
